name: Loop - Autonomous Implementation

on:
  issues:
    types: [labeled]
  workflow_dispatch:
    inputs:
      spec:
        description: 'Task specification'
        required: true
        type: string
      budget:
        description: 'Budget limit in dollars'
        required: false
        default: '25'
        type: string
      max_iterations:
        description: 'Maximum iterations'
        required: false
        default: '10'
        type: string

jobs:
  loop:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event.label.name == 'loop'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine spec
        id: spec
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "spec<<EOF" >> $GITHUB_OUTPUT
            echo "${{ inputs.spec }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "spec<<EOF" >> $GITHUB_OUTPUT
            echo "${{ github.event.issue.body }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Run Loop
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          prompt: |
            /loop:start

            Spec:
            ${{ steps.spec.outputs.spec }}
          max_turns: 50
          allowed_tools: "Read,Write,Edit,Bash,Glob,Grep,TaskCreate,TaskUpdate,TaskGet,TaskList"
        env:
          LOOP_BUDGET: ${{ inputs.budget || '25' }}
          LOOP_MAX_ITERATIONS: ${{ inputs.max_iterations || '10' }}
          LOOP_HEADLESS: "true"

      - name: Create PR with changes
        if: success()
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat: loop automated implementation"
          title: "[Loop] ${{ github.event.issue.title || 'Automated Implementation' }}"
          body: |
            ## Automated by Loop

            **Source:** ${{ github.event_name == 'issues' && format('Issue #{0}', github.event.issue.number) || 'Manual trigger' }}

            ### Spec
            ```
            ${{ steps.spec.outputs.spec }}
            ```

            ### Configuration
            - Budget: ${{ inputs.budget || '25' }}
            - Max Iterations: ${{ inputs.max_iterations || '10' }}

            ---
            *Generated by [loop](https://github.com/your-org/moo.md/tree/main/loop)*
          branch: loop/${{ github.run_id }}
          delete-branch: true

      - name: Comment on issue
        if: github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '**Loop completed.** Check the PR for implementation details.'
            })
