loop:
  stage: build
  image: node:20

  rules:
    - if: $CI_PIPELINE_SOURCE == "trigger"
      when: always
    - if: $LOOP_SPEC != null
      when: always
    - when: never

  variables:
    LOOP_BUDGET: ${LOOP_BUDGET:-25}
    LOOP_MAX_ITERATIONS: ${LOOP_MAX_ITERATIONS:-10}
    LOOP_HEADLESS: "true"

  before_script:
    - npm install -g @anthropic-ai/claude-code

  script:
    - |
      claude --print \
        --allowedTools "Read,Write,Edit,Bash,Glob,Grep,TaskCreate,TaskUpdate,TaskGet,TaskList" \
        --max-turns 50 \
        "/loop:start

        Spec:
        ${LOOP_SPEC}"

    - |
      if [ -n "$(git status --porcelain)" ]; then
        git config user.email "loop@ci.local"
        git config user.name "Loop Bot"
        git checkout -b loop/${CI_PIPELINE_ID}
        git add -A
        git commit -m "feat: loop automated implementation"
        git push origin loop/${CI_PIPELINE_ID}
      fi

  artifacts:
    paths:
      - "**/*"
    expire_in: 1 week
    when: always


loop:manual:
  extends: loop
  rules:
    - when: manual
  variables:
    LOOP_SPEC: "Define spec via CI variables"


loop:from-issue:
  extends: loop
  rules:
    - if: $CI_PIPELINE_SOURCE == "issue"
  variables:
    LOOP_SPEC: ${CI_ISSUE_DESCRIPTION}
