# Test: product:product triggers on PRD/product tasks
---
name: product-triggers-on-prd-request
description: Product skill should auto-activate on PRD, competitive analysis, metrics tasks
category: skill-trigger
plugin: product
skill: product

prompt: "I need to write a PRD for a new notifications system. Help me define the requirements."

model_tier: sonnet
timeout_ms: 120000

evaluators:
  - trigger-evaluator:
      expected_skill: "product:product"
      pass_threshold: 0.70

expected_behaviors:
  - "Product skill activates on PRD requests"
  - "Routes to appropriate workflow (prd, compete, metrics)"
  - "Asks clarifying questions about requirements"
  - "Mentions product management frameworks"

tags: [core, regression, phase1]
created: 2024-12-15
