// Central registry infrastructure. DO NOT edit this file to add features —
// features self-register by importing `register` from here (see handlers/).
export const routes = {};
export const schemas = {};

export function register(path, handler, schema) {
  if (routes[path]) throw new Error(`duplicate route ${path}`);
  routes[path] = handler;
  schemas[path] = schema;
}
